### ISSUE TITLE
IE11 tests stall

### ISSUE THREAD

**Issue by feross** [defunctzombie/zuul#121]
It's probably a sauce labs issue, but is anyone else seeing this?

```
- waiting: <internet explorer 11 on Windows 2012 R2>
- waiting: <internet explorer 11 on Windows 2012 R2>
- waiting: <internet explorer 11 on Windows 2012 R2>
- waiting: <internet explorer 11 on Windows 2012 R2>
- waiting: <internet explorer 11 on Windows 2012 R2>
- waiting: <internet explorer 11 on Windows 2012 R2>
- waiting: <internet explorer 11 on Windows 2012 R2>
- waiting: <internet explorer 11 on Windows 2012 R2>
- waiting: <internet explorer 11 on Windows 2012 R2>
- waiting: <internet explorer 11 on Windows 2012 R2>
- waiting: <internet explorer 11 on Windows 2012 R2>
- waiting: <internet explorer 11 on Windows 2012 R2>
- waiting: <internet explorer 11 on Windows 2012 R2>
- waiting: <internet explorer 11 on Windows 2012 R2>
- waiting: <internet explorer 11 on Windows 2012 R2>
- waiting: <internet explorer 11 on Windows 2012 R2>
- waiting: <internet explorer 11 on Windows 2012 R2>
- waiting: <internet explorer 11 on Windows 2012 R2>
- waiting: <internet explorer 11 on Windows 2012 R2>
- waiting: <internet explorer 11 on Windows 2012 R2>
- waiting: <internet explorer 11 on Windows 2012 R2>
- waiting: <internet explorer 11 on Windows 2012 R2>
- waiting: <internet explorer 11 on Windows 2012 R2>
- waiting: <internet explorer 11 on Windows 2012 R2>
- waiting: <internet explorer 11 on Windows 2012 R2>
```

**Comment by feross** [comment]
This was my fault. Sorry for the false alarm.

**Comment by Charlotteis** [comment]
Hi @feross I am having the same problem, how did you fix yours? Any help would be appreciated!

**Comment by feross** [comment]
It was a bug in my tests. Try running IE11 locally, or use the saucelabs remote UI, to find your issue.

**Comment by vvo** [comment]
@feross I added a new browser_timeout parameter for this recently, mostly because tape does not catches uncaught exceptions since 4.0, I will also handle this case in zuul soon

**Comment by vvo** [comment]
@Charlotteis most of the time the issue comes from an uncaught exception or test timeout being not reported by mocha etc.

**Comment by Charlotteis** [comment]
@vvo @feross thanks both for the suggestions

**Comment by davidtheclark** [comment]
So is there no way to get a more useful message in these cases of everlasting `waiting`?

I don't have easy access to the browsers that I'm running via SauceLabs, so if I don't see some meaningful log of what's happening it will be very hard to debug.

**Comment by defunctzombie** [comment]
Console output should be going to your terminal so if you want to print some info about the tests being run that might help trace it down. Alternatively, what I do is fire up saucelabs manually and run zuul with the --tunnel option. That will generate a public facing URL which you can load up into saucelabs manual run and do some poking around in the dev tools to see what is broken.

**Comment by davidtheclark** [comment]
Thanks!
