### ISSUE TITLE
handling multiple test files

### ISSUE THREAD

**Issue by maraoz** [defunctzombie/zuul#122]
I'm having problems using zuul with many test files. What's the usual method for that?

I'm getting the following error:
```
$ zuul --local 8080 -- test/*/*.js
open the following url in a browser:
http://localhost:8080/__zuul

/usr/lib/node_modules/zuul/node_modules/convert-source-map/index.js:109
  var m = content.match(commentRx);
                  ^
RangeError: Maximum call stack size exceeded
```

**Comment by maraoz** [comment]
Same problem if I do:

```
$ find test/ -type f -name "*.js" | xargs zuul --local 8080
 --
open the following url in a browser:
http://localhost:8080/__zuul

/usr/lib/node_modules/zuul/node_modules/convert-source-map/index.js:109
  var m = content.match(commentRx);
                  ^
RangeError: Maximum call stack size exceeded
```

**Comment by defunctzombie** [comment]
I don't think it supports nested wildcards like that.

**Comment by maraoz** [comment]
My second usage example doesn't include wildcards. It's equivalent to calling `zuul` with a list of files.
How do you usually use `zuul` with many test files?

**Comment by defunctzombie** [comment]
I just use wildcards: 
https://github.com/defunctzombie/int/blob/master/package.json#L24

I believe a list of files also works:
https://github.com/visionmedia/superagent/blob/master/Makefile#L22

**Comment by defunctzombie** [comment]
I think there is some other issue, not the multiple source files. Maybe one of your files contains something causing the source map conversion to break. Would be good to look into that specifically and open an issue about that.

**Comment by maraoz** [comment]
I'll try the files one by one and report back
