### ISSUE TITLE
tape test.only does not work when using zuul

### ISSUE THREAD

**Issue by vvo** [defunctzombie/zuul#138]
I am trying to use https://github.com/substack/tape#testonlyname-cb along with zuul but it's not working as expected: all tests will run even if using .only on a specific test.

Is this something easy to fix?

**Comment by thewazir** [comment]
Could you share your test code? I was able to get
```javascript
test.only('should return an object',
 function (t){
  var result = uniqCharacters('foo','foo');
  t.equal(Object.prototype.toString.call(result).slice(8,-1),'Object');
  t.end();
});
```
to be the only test plan to execute from my repo https://github.com/thewazir/unique-characters
The test ran locally and in SauceLabs.

**Comment by vvo** [comment]
@thewazir sorry it works as expected, weird
