### ISSUE TITLE
browser field, allow version: stable..dev ?

### ISSUE THREAD

**Issue by vvo** [defunctzombie/zuul#146]
Should we allow and interpret what a people may want to do: test from stable version up to dev channel (firefox, chrome)?

I added a note in the wiki to do so but wondering if we should also detect "stable": https://github.com/defunctzombie/zuul/wiki/Cloud-testing#3-select-browsers-to-test

**Comment by defunctzombie** [comment]
What would `stable` mean?

**Comment by vvo** [comment]
The version right before beta in the version list (works for chrome and firefox)

**Comment by vvo** [comment]
But as I discovered, being explicit for the stable version is a lot more easy to understand so no need for this.
