### ISSUE TITLE
Why do we extract the sourcemaps from the bundles?

### ISSUE THREAD

**Issue by vvo** [defunctzombie/zuul#151]
I want to understand Why do we need to extract the sourcemaps from the browserify bundle and load them separetely? Doesn't it work out of the box?

I am asking this because, we both load the test bundle and test bundle sourcemap synchronously from the test-client.js file, resulting in synchronous javascript loading (instead of having the test-bundle right into the webpage.html with embedded sourcemaps).

Thanks.

**Comment by defunctzombie** [comment]
I think it had something to do with providing better stacktraces. Do you remember @thlorenz

**Comment by vvo** [comment]
For reference, I do not want to break things for performance (that's silly) but loading these files synchronously result in the testing process starting a lot slower than what it could be.

**Comment by thlorenz** [comment]
Yeah we are using the source-map.json thingys to fill in our stacktraces with actual locations.
