### ISSUE TITLE
[question] documentation on supported platform and config format?

### ISSUE THREAD

**Issue by maraoz** [defunctzombie/zuul#154]
Hey,
I'm using zuul for a while, great tool. I've recently wanted to add more platforms to the tests, but couldn't find any comprehensive list of the supported browsers, other than: https://saucelabs.com/platforms/
and I have no idea what the syntax is to setup tests in Android or iOS. 
Is there a doc you can point me to? If it helps, I can write a PR to include this info somewhere in zuul's docs

**Comment by defunctzombie** [comment]
I think we should make a zuul flag to list platforms and browsers to make this easier for users.

Saucelabs doesn't provide any good UI to discover this. Here is a link to the API backend we use to actually figure stuff out in zuul (https://saucelabs.com/rest/v1/info/browsers/webdriver). That at least gets you somewhere tho not ideal.

Android platform is just `android` and ios is `iphone`

/cc @rase-

**Comment by maraoz** [comment]
@defunctzombie thanks!

**Comment by rase-** [comment]
@maraoz Actually Zuul already has a flag called `--list-available-browsers` that can list the browser names, versions and platforms for you.

We should make sure this is in the documentation.

**Comment by rase-** [comment]
Updated the cloud testing wiki page with this information.

**Comment by maraoz** [comment]
@rase- thanks for that info! :)
