### ISSUE TITLE
How to specify float number version with range (7.1..latest)?

### ISSUE THREAD

**Issue by MoOx** [defunctzombie/zuul#167]
I've tried this in my yml conf
I want to combine array + range + float (in order to reduce build time by only test on patched major releases)

- `version: [6.1, 7.1..latest]`: zuul error (make sense since wiki ask for quote for float number)
- `version: ['6.1', '7.1'..latest]`: parsing error on ..latest
- `version: ['6.1', '7.1..latest']`: zuul error (same as before, see trace below)

---

Btw I get weird error (stack trace is in one line)

```console
$ zuul -- dist/test.js

/.../node_modules/zuul/lib/flatten_browser.js:133
                    throw new Error('unable to find start version: ' + start);
                          ^
process_version_str (/.../node_modules/zuul/lib/flatten_browser.js:133:27),/.../node_modules/zuul/lib/flatten_browser.js:69:47,Array.forEach (native),/.../node_modules/zuul/lib/flatten_browser.js:68:32,Array.forEach (native),flatten (/.../node_modules/zuul/lib/flatten_browser.js:12:13),/.../node_modules/zuul/bin/zuul:212:19,IncomingMessage.<anonymous> (/.../node_modules/zuul/lib/scout_browser.js:35:13),IncomingMessage.g (events.js:199:16)
```

Not sure if it's related to my env.

**Comment by MoOx** [comment]
I also tried this ` "'7.1'..latest"`, same issue.

**Comment by vvo** [comment]
Not sure this is supported.

About quoting floating versions, this is because yamljs will parse 8.0 (float) to 8 (integer). And iPhone 8.0 is iPhone 8.0, not 8.

**Comment by defunctzombie** [comment]
Would be good to support this. Not sure of the best representation format tho. Can we make the parser just handle something like `1.3..latest`? I don't think any browsers use patch versions so just detecting `#.#` might be good enough.

**Comment by rase-** [comment]
Aye.

**Comment by rase-** [comment]
I can take a stab at this later today.

**Comment by MoOx** [comment]
Or we can split by ".." to get left and right values ?

**Comment by rase-** [comment]
Looks like this works:

```
 - name: iphone
    version: ['5.0', '5.1', 6.0..latest]
```

```
- testing: iphone @ Mac 10.6: 5.0
- testing: iphone @ Mac 10.8: 5.1 6.0 6.1
- testing: iphone @ Mac 10.9: 7.0 7.1
- testing: iphone @ Mac 10.10: 8.0 8.1
```

**Comment by rase-** [comment]
And this seems to work great too:

```
  - name: iphone
    version: ['5.0', '5.1', 6.0..7.1]
```

```
- testing: iphone @ Mac 10.6: 5.0
- testing: iphone @ Mac 10.8: 5.1 6.0 6.1
- testing: iphone @ Mac 10.9: 7.0 7.1
```

**Comment by rase-** [comment]
Also:

  - name: iphone
    version: ['5.0', '5.1', '6.0..7.1']
```

```
- testing: iphone @ Mac 10.6: 5.0
- testing: iphone @ Mac 10.8: 5.1 6.0 6.1
- testing: iphone @ Mac 10.9: 7.0 7.1
```

and

  - name: iphone
    version: '6.0..7.1'
```

```
- testing: iphone @ Mac 10.8: 6.0 6.1
- testing: iphone @ Mac 10.9: 7.0 7.1
```

**Comment by rase-** [comment]
I updated the cloud testing wiki page after the above experimentation. I don't think we need to change anything right now since SauceLabs only provides versions up to `x.y` so I'll close for now.

Please do reopen if anything else comes up. :)

**Comment by MoOx** [comment]
I will try that. Good to know. Thanks !
