### ISSUE TITLE
Exception not handled about open_tunnel.url

### ISSUE THREAD

**Issue by MoOx** [defunctzombie/zuul#169]
Not sure what I changed recently (just a few lines) and I am getting this

```console
$ zuul -- dist/test.js

- testing: chrome @ Windows 2012 R2: 39 40

/.../node_modules/zuul/node_modules/zuul-localtunnel/index.js:22
    var url = open_tunnel.url + '/__zuul';
                         ^
/.../node_modules/zuul/node_modules/zuul-localtunnel/index.js:22:26,/.../node_modules/zuul/node_modules/zuul-localtunnel/node_modules/localtunnel/client.js:312:20,/.../node_modules/zuul/node_modules/zuul-localtunnel/node_modules/localtunnel/client.js:283:20,Request._callback (/.../node_modules/zuul/node_modules/zuul-localtunnel/node_modules/localtunnel/client.js:206:24),Request.self.callback (/.../node_modules/zuul/node_modules/zuul-localtunnel/node_modules/localtunnel/node_modules/request/main.js:122:22),Request.emit (events.js:110:17),Request.<anonymous> (/.../node_modules/zuul/node_modules/zuul-localtunnel/node_modules/localtunnel/node_modules/request/main.js:655:16),Request.emit (events.js:129:20)
```

This doesn't help a lot :/

**Comment by rase-** [comment]
This exception is highly unexpected, so I doubt it should be handled. Do you have local changes to Zuul itself?

**Comment by rase-** [comment]
Hmm the issue itself looks like for some reason `localtunnel` is unable to provide a url.

**Comment by MoOx** [comment]
I just get the same issue on travis :/ (so fresh zuul module)

**Comment by rase-** [comment]
@MoOx ok that just happened to me too. I think there's something wrong with localtunnel.

cc @defunctzombie

**Comment by rase-** [comment]
Without making any changes that is.

**Comment by MoOx** [comment]
Good to know the issue is not just for me.
But ouch.

![screen shot 2015-03-03 at 16 12 01](https://cloud.githubusercontent.com/assets/157534/6465240/0c056a58-c1c0-11e4-81c2-cadd942b6c26.png)

So I am guessing this case should be handled :(

**Comment by rase-** [comment]
Should probably be handled in the localtunnel module though.

**Comment by MoOx** [comment]
zuul-localtunnel, sure.

**Comment by rase-** [comment]
Now has a better error since https://github.com/defunctzombie/zuul/commit/583190205e40ec2c8ced79b7ee6944ff65f5d9b0

Thanks @MoOx!

**Comment by rase-** [comment]
You'll see

```
Error: localtunnel server returned an error, please try again
```

from now on.

**Comment by rase-** [comment]
@MoOx looks like `lt` is back! :)

**Comment by MoOx** [comment]
I just pinged the interested person on twitter ;)
