### ISSUE TITLE
Get config from env vars?

### ISSUE THREAD

**Issue by ericelliott** [defunctzombie/zuul#173]
Of course, it's not a good idea to check your credentials into github... can we pass them as env vars instead of getting them from the `.yml` config?

**Comment by rase-** [comment]
By credentials you mean saucelabs credentials? This is already possible:https://github.com/defunctzombie/zuul/blob/master/bin/zuul#L170

**Comment by rase-** [comment]
Also documented here for use with travis: https://github.com/defunctzombie/zuul/wiki/Travis-ci#5-final-step

**Comment by ericelliott** [comment]
:+1:
