### ISSUE TITLE
job level public

### ISSUE THREAD

**Issue by adrai** [defunctzombie/zuul#176]
How can I set the job level to public?

**Comment by defunctzombie** [comment]
No idea what that even means. Can you point to some docs? I assume you are talking about something Saucelabs related. This issue needs a much better description.

**Comment by adrai** [comment]
Sorry...

See here: https://docs.saucelabs.com/reference/test-configuration/

"public": "team"
The available visibility levels are as follows:

public

Making your test public means that it is accessible to everyone, and may be listed on public web pages and indexed by search engines.

**Comment by adrai** [comment]
ok, created a new (OpenSauce) account... closing this issue...
