### ISSUE TITLE
Browserify configuration from zuul.yml isn't applied in order

### ISSUE THREAD

**Issue by mcous** [defunctzombie/zuul#177]
I've been running into an issue with the browserify-builder: the way the configure function is set up, any configuration from zuul.yml will be applied in the order ['plugin', 'external', 'ignore', 'exclude', 'transform', 'add', 'require'], regardless of where they appear in configuration.

The reason I need them to be applied in the order I specify is that if my tests and/or source is/are written in coffee (sorry not sorry) I need the coffeeify transform to happen before any plugins (e.g. proxyquire-universal).

I hacked together a little fix, and I'd be happy to PR with some cleanup and tests, but figured I'd open an issue up first to check. Let me know if this seems like necessary functionality.

**Comment by defunctzombie** [comment]
Seems like something that should be fixed. Lets take a look at your PR and we will know more :)
