### ISSUE TITLE
Configuration through JS

### ISSUE THREAD

**Issue by andreypopp** [defunctzombie/zuul#183]
Here is a proposal to allow configuration of zuul through JS.

Let there be `zuul.config.js` which takes precedence over `zuul.yaml` (we should warn if both exist though). The file is a CommonJS module which exports zuul config as an object:
```
module.exports = {
  ui: 'mocha',
  browsers: [
    {name: 'chrome',
     version: 'latest'},
    {name: 'safari',
     version: 'latest'}
  ],
  ...
}
```

Pros:
* Configuration based on environment variables
* Configuration hooks for builders (a callback which configures browserify, so we don't have to track its API closely)
* Using JS for functions/modules (for example if we need to maintain multiple test configurations)
* JS is more familiar than YAML

Cons:
* It's executable code, there can be additional security risks... (not sure how much we concerned with that though given that a lot of tools do the same)
* Not as much declarative as yaml (what does it even mean?)

**Comment by defunctzombie** [comment]
I wouldn't be against it. `That is basically my way of saying I would want to see a PR but wouldn't code it myself anytime soon :)`

/cc @rase-

**Comment by rase-** [comment]
Sounds good to me. I can take a look at this later today or tomorrow.

**Comment by mightyiam** [comment]
:+1:

I would like to do
```js
module.exports = {
  ui: 'mocha',
  browsers = require('my-company-official-supported-browsers')
}
```

**Comment by vvo** [comment]
Programmatic settings of the browsers variable itself is VERY interesting. I actually need it for a project of mine: so that I can have different build matrixs in travis (simple, mobile, all browsers..).

I first thought I would need to do a PR to zuul to allow setting a different config file (in fact, it may be also useful).

:+1: 

I am not sure thought we should keep both .zuul.yml and .zuul.js, it may be confusing? At least in the docs, we should only advocate for one configuration type, but keep yml for backward compat?

**Comment by andreypopp** [comment]
@vvo did you see my linked PR?

I think `zuul.config.js` is a better filename than `.zuul.js` cause it is somewhat consistent with other players like Karma (`karma.config.js`), Webpack (`webpack.config.js`). Also, no reason to start filename with `.`.

> I first thought I would need to do a PR to zuul to allow setting a different config file (in fact, it may be also useful).

I think config from js solves more problems at once, including better API builder configuration (webpack and browserify).

> I am not sure thought we should keep both .zuul.yml and .zuul.js, it may be confusing? At least in the docs, we should only advocate for one configuration type, but keep yml for backward compat?

I'm :+1: for keeping both backward compat but documenting only js config story.

**Comment by mightyiam** [comment]
Hurray! And thanks!

**Comment by defunctzombie** [comment]
All the thanks go to @andreypopp for doing the work and following through

**Comment by defunctzombie** [comment]
@andreypopp could you add a page to the wiki about this please

**Comment by andreypopp** [comment]
Will do. Do you think we should keep docs for yaml config or are we going
to deprecate it at some point?

**Comment by defunctzombie** [comment]
We should keep it.

**Comment by vvo** [comment]
@andreypopp This is great and was merged. Can you enhance the wiki by giving the same .zuul.yml example in JavaScript? Thanks.
