### ISSUE TITLE
Any idea how to add timeout ?

### ISSUE THREAD

**Issue by MoOx** [defunctzombie/zuul#185]
I am running a very "simple" file that is just a glob of some tests/*.js test files written with tape.
Everything works fine on a lot of environnements, EXCEPT (here is the fun part) on IE 10/9/8 where I am probably getting errors. That being said (I don't really know how zuul run) I am not getting breaking errors on SauceLabs (or it seems so). The immediate (and really annoying) consequence is that build stop after around 30min (which consume a lot of "credits" for private project) when some other builds take 10~20s).
Is there a way to add a timeout in order to avoid this kind of behavior (as an option) ?

**Comment by vvo** [comment]
There is no such feature as for now if I am not mistaken.

1. It would be a good addition
 1. Do you want a per-browser setting or a global zuul timeout?
 1. In both way it would go into zuul.yml, then read and used by https://github.com/defunctzombie/zuul/blob/9240b977464364aee675281838a0140b5e5a7999/lib/zuul.js#L67, which would call .shutdown on the browser(s) when the timeout passed

Also, if you want to debug your tests on IE, either use https://github.com/xdissent/ievms. Or you can use `zuul --local 8080 --ui mocha-qunit -- test.js` then ngrok or localtunnel to create a public url to your local test and open it in saucelab manual IE testing sessions

**Comment by MoOx** [comment]
A global option in zuul.yml lgtm.

Don't worry, I already have some VMs and I am using testem for local testing for now, it's better for my needs (handle multiple browsers easily).
