### ISSUE TITLE
Can't install via npm: HTTP 406 from github for defunctzombie/stacktrace.js#07e7b95

### ISSUE THREAD

**Issue by yourcelf** [defunctzombie/zuul#188]
When trying to install zuul via npm, I'm getting an HTTP 406 from github for the dependency ``"defunctzombie/stacktrace.js#07e7b95"``.  At first I thought this was a symptom of github's DDoS, but it looks like this arises from not having a fully-qualified URL with "git://" protocol in the package.json.

In short, npm is trying to resolve this dependency as ``https://github.com/defunctzombie/stacktrace.js#07e7b95``; github now returns a 406 for this; but it would work fine to instead use ``git://github.com/defunctzombie/stacktrace.js#07e7b95``.

It looks like npm will be [working around this](https://github.com/npm/npm/issues/7630) in a future release, but it'd be good to fix it here so non-bleeding-edge npm users can still install zuul.

**Comment by smmoosavi** [comment]
Is there any solution?

```
$ npm i -g zuul
npm ERR! fetch failed https://github.com/defunctzombie/stacktrace.js#07e7b95
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 406
```

**Comment by vvo** [comment]
@defunctzombie PR is ready, #193

**Comment by vvo** [comment]
@smmoosavi in the meantime you can:

```sh
npm update npm -g
npm install zuul -g
```

let use know
