### ISSUE TITLE
.config/.zuul.yml

### ISSUE THREAD

**Issue by shannonmoeller** [defunctzombie/zuul#200]
As more and more tools have become best-practice when authoring npm modules, from `package.json` to `.*rc` to `*file.js`, the root directory of projects has become a very loud place. This dot-noise pushes README content farther and farther down the main page of git repos.

![screenshot 2015-05-01 21 41 51](https://cloud.githubusercontent.com/assets/155164/7439468/e8f2ff9e-f04a-11e4-8c1b-4248379053e9.png)

What if the above could optionally be simplified to the following?

![screenshot 2015-05-01 21 50 12](https://cloud.githubusercontent.com/assets/155164/7439513/179455c2-f04c-11e4-9577-c3b73c2b01c3.png)

This is a simple example and that's already about a 30% vertical space savings. I started the conversation over in the [npm repo](https://github.com/npm/npm/issues/8159), but I'm also submitting issues to the `findup`, `findup-sync`, `karma`, and `travis-ci` repos.

**Comment by shannonmoeller** [comment]
@defunctzombie Thanks for your consideration.

**Comment by defunctzombie** [comment]
@shannonmoeller I am not against this but would only do it if the other projects were interested. I also don't feel that strongly about it and don't find the root dir file clutter a serious problem.

**Comment by hax** [comment]
@defunctzombie Wait other projects and other project wait others cause a DEAD LOCK.
