### ISSUE TITLE
Update mocha?

### ISSUE THREAD

**Issue by metasansana** [defunctzombie/zuul#201]
Is there a blocker somewhere?

In `package.json` I see `"mocha": "~1.16.2"` mocha [added](https://github.com/mochajs/mocha/blob/master/HISTORY.md#1180--2014-03-13)  promise support in `1.18.0`

I'm guessing this is why I can't simply do this: 

```javascript

describe('A test of epic proportions', function() {

 return api.makeAsyncCall().
  then(function(result) {
     assert(result);
  })
});

//The above is not waited on.
```

**Comment by defunctzombie** [comment]
The mocha version is baked in cause I can't just require mocha browser side using browserify (last time I checked). I would not be against bumping the internal version used tho.

**Comment by ngryman** [comment]
:+1:
