### ISSUE TITLE
How to specify N latest versions for browsers in .zuul.yml?

### ISSUE THREAD

**Issue by dfilatov** [defunctzombie/zuul#209]
Am I missed something in documentation? But I couldn't find any information how to specify N latest versions.

**Comment by vvo** [comment]
What does "N latest versions" means? Can you be more specific @dfilatov

**Comment by dfilatov** [comment]
For instance, I'd like to specify: three latest available versions of Chrome

**Comment by vvo** [comment]
No it's not possible but that's a great idea!

What would be the API for such a feature?

**Comment by dfilatov** [comment]
Maybe something like this: `version: latest(3)`

**Comment by vvo** [comment]
Not sure this is YAML compatible.

We need to find a good way to do what you want to do and having an API that is ok in yaml and JS.

**Comment by dfilatov** [comment]
I believe you'll find the best way to do what I want. )

**Comment by dfilatov** [comment]
btw, thanks for great tool!

**Comment by vvo** [comment]
I just find it hard to find an API to express "latest 3 versions" that is easy to parse while being readable, while not being "latest 3 versions" :)

**Comment by dfilatov** [comment]
Take a look how such cases are specified in [autoprefixer](https://github.com/postcss/autoprefixer#browsers): `last 2 versions`.

**Comment by vvo** [comment]
woo browserlist is amazing, we could leverage it maybe and then map to saucelabs browsers

**Comment by dfilatov** [comment]
It would be awesome!

**Comment by vvo** [comment]
> It would be awesome!

If you feel adventurous, take some time to do a PR. Will not do it :smile_cat:

**Comment by defunctzombie** [comment]
+1 for this feature. Would certainly accept a PR. Dunno if/when we will be able to get to it tho.

**Comment by mcous** [comment]
I think this issue can be closed since #231 added this functionality in v3.4.0.
