### ISSUE TITLE
Zuul mishandles file globs

### ISSUE THREAD

**Issue by chinedufn** [defunctzombie/zuul#210]
The use of `path.resolve` [here](https://github.com/defunctzombie/zuul/blob/master/lib/control-app.js#L34) will not properly expand valid file globs. Example: `test/**/*.js`

This causes zuul to log errors whenever you try to run tests using wildcard subdirectory globs

**Comment by vvo** [comment]
Yes to circumvent this I had run.js which did a https://www.npmjs.com/package/bulk-require + https://github.com/substack/bulkify

**Comment by chinedufn** [comment]
That's nice stuff!

But it looks like those are both dev-dependencies. What about when you the end user passes zuul globs?

Problematic:

```sh
zuul --local 9966 -- test/**/*.js
```

This gets solved by something like - https://github.com/chinedufn/zuul/blob/wild-subdir/lib/control-app.js#L34-L40
