### ISSUE TITLE
Documentation and zuul versions

### ISSUE THREAD

**Issue by xgbuils** [defunctzombie/zuul#212]
I'm starting to read documentation and there is an issue.

In [installation](https://github.com/defunctzombie/zuul/wiki/installation) is suggested to install zuul CLI:
``` bash
$ sudo npm install -g npm
$ zuul -V
3.0.0
```

However in [Travis ci](https://github.com/defunctzombie/zuul/wiki/Travis-ci#4-create-a-packagejson-file) is suggested install 1.0.1 version of zuul.

This has meant that when I run "npm test"(v1.01) it works but when I run "zuul -- test"(v3.0.0) not.

**Comment by vvo** [comment]
@xgbuils I think the travis documentation in the wiki is only old on the version side, you can update it please?

**Comment by vvo** [comment]
Nice :)

It seems like anyone can edit a wiki on github, wtf? @defunctzombie

**Comment by xgbuils** [comment]
> It seems like anyone can edit a wiki on github, wtf? @defunctzombie
Two issues for the price of one. ;-)

**Comment by defunctzombie** [comment]
Yea, I believe the wiki is completely open for editing by anyone currently. I can restrict it to collaborators only if we are having problems with bad edits.

**Comment by vvo** [comment]
@defunctzombie That's really fine so, easier collaboration
