### ISSUE TITLE
tests are failing

### ISSUE THREAD

**Issue by defunctzombie** [defunctzombie/zuul#244]
@vvo https://travis-ci.org/defunctzombie/zuul

Looks like some recent changes cause tests to no longer be passing. Should be fixed before we release another version.

**Comment by vvo** [comment]
I have another project with failing test. Seems saucelabs cannot start ios 9.1..

**Comment by defunctzombie** [comment]
Do we know someone from saucelabs following this project we can ping?

**Comment by vvo** [comment]
Here's what I got when trying to debug my failing iphone 9.1 starts: 

![2015-10-23-112028_850x833_scrot](https://cloud.githubusercontent.com/assets/123822/10689019/7a87b5d8-7978-11e5-9e1a-54fb27efc505.png)

cc @sebv any hints?

**Comment by vvo** [comment]
Fixed them in d00f5e7761d0d4074e60e3c521a718683da14a4b, seems like iphone/ipad 9.1 are having issues since some good time. I was not able to make them work on multiple projects I have. Sadly

**Comment by vvo** [comment]
![2015-10-23-140640_1221x217_scrot](https://cloud.githubusercontent.com/assets/123822/10692109/4b2ca5fc-798f-11e5-9ed4-8b201932c3e3.png)

**Comment by vvo** [comment]
also reduced test time to 3 min instead of 10
