### ISSUE TITLE
Update path to istanbul assets

### ISSUE THREAD

**Issue by kof** [defunctzombie/zuul#245]
Files like this one are moved in instanbul to assets dir.

zuul/node_modules/istanbul-middleware/node_modules/istanbul/lib/vendor/prettify.css

**Comment by defunctzombie** [comment]
@vvo ping, something from a recent update?

**Comment by vvo** [comment]
@lpinca any hints? You did an istanbul related PR.

**Comment by vvo** [comment]
Also @kof I am not sure to understand what you are asking for, can you be more specific on what's wrong?

**Comment by kof** [comment]
just install the latest version, remove node_modules and you will get it when you run some tests locally, it will try to load some files from a non-existing location.

**Comment by vvo** [comment]
I still don't get how to fix this eheh.

**Comment by lpinca** [comment]
I can reproduce this and yes it is caused by the `istanbul-middleware` update (my pr).
If you pin down `istanbul` to version `0.2.x` in `instabul-middleware`, it works. A newer `istanbul` generates this isse.

I will try to investigate as soon as I find some time.

To repoduce the issue:

1. Install latest `zuul`
2. run `zuul --local 8080 -- test.js`

**Comment by defunctzombie** [comment]
@vvo lets revert the update since it seems to break for users and needs more testing

**Comment by vvo** [comment]
Allright

**Comment by vvo** [comment]
Ok published 3.7.2 with reverted istanbul-middleware, @lpinca would be good to get your insights when you have time :D

**Comment by lpinca** [comment]
@vvo sure I will take a look, I just have to find a little time :smile:

**Comment by lpinca** [comment]
https://github.com/gotwarlost/istanbul/pull/467
https://github.com/gotwarlost/istanbul-middleware/pull/26

`istanbul-middleware@0.2.1` is broken, we have to wait for the next version.

**Comment by vvo** [comment]
Nice, open a new PR when ready then :)
