### ISSUE TITLE
Using ngrok instead of localtunnel

### ISSUE THREAD

**Issue by sebpiq** [defunctzombie/zuul#246]
Hi! I was wondering if there is any way to use ngrok instead of localtunnel? I have a websocket server running on my machine through zuul for my tests, and I can't get tests to work. On the other hand, with ngrok it works perfectly.

**Comment by defunctzombie** [comment]
https://www.npmjs.com/package/zuul-ngrok

**Comment by sebpiq** [comment]
great! Thanks

**Comment by sebpiq** [comment]
Though this is not very clear how to use that package ...
