### ISSUE TITLE
Skip tests in Travis PRs

### ISSUE THREAD

**Issue by feross** [defunctzombie/zuul#259]
When running sauce labs tests on travis, secure credentials aren't available to pull requests for security reasons. Travis documents the reasons [here](https://docs.travis-ci.com/user/pull-requests#Security-Restrictions-when-testing-Pull-Requests).

The effect of this is that all pull requests fail because zuul can't find the sauce labs credentials. Can we add an option to automatically pass the tests if sauce labs credentials aren't found? Or perhaps, just skip the tests when the `TRAVIS_PULL_REQUEST` environment variable is `'true'`?

**Comment by vvo** [comment]
Why not do this inside your project instead?

**Comment by defunctzombie** [comment]
We could add an option to pass if no creds founds, but I think @vvo has a point in that you could just easily bypass after env var detection today with some bash.

Separately, I think it is pretty reasonable to just have the creds for open source projects be open so that PRs get tested since you want that to happen.

**Comment by vvo** [comment]
> I think @vvo has a point in that you could just easily bypass after env var detection today with some bash.

That's what I do in my tests right now.

> Separately, I think it is pretty reasonable to just have the creds for open source projects be open so that PRs get tested since you want that to happen.

Yes I saw some projects doing so

**Comment by parshap** [comment]
I do something similar by [checking environment variables to determine what test command to run](https://github.com/parshap/node-sanitize-filename/blob/2bfbf0ce18608cc24d199049bf120afb1aa2d4a8/.travis.yml#L44). I think this makes more sense than having something built into zuul.

**Comment by feross** [comment]
Fair enough. Thanks for the feedback guys.
