### ISSUE TITLE
Weird build failure error

### ISSUE THREAD

**Issue by bitinn** [defunctzombie/zuul#279]
Here is something I am observing but not able to figure out:

I have 2 builds, both perfectly fine in terms of testcases, both using the same credential, but one reports passed, another reports `Zuul tried to run tests in saucelabs, however no saucelabs credentials were provided`.

I thought it was the usual Travis / Saucelabs issue, but re-run failed on the same error.

https://github.com/bitinn/vdom-parser/blob/master/.travis.yml
https://travis-ci.org/bitinn/vdom-parser/builds/117270826
https://travis-ci.org/bitinn/vdom-parser/builds/121846815

What's happening here? Is the error misleading?

**Comment by bitinn** [comment]
Looks like the cause is incorrect credential (I have regenerated and recreated them and now it works)

Not sure why, because the old encrypted api key worked a week earlier.

I would suggest changing the error message to include possible incorrect credential...

**Comment by vvo** [comment]
> I would suggest changing the error message to include possible incorrect credential...

This would trigger possibly a leak of credentials in debug logs

Not sure we are able to differentiate no credentials from bad credentials, maybe a simple if, care to add it? thanks

**Comment by bitinn** [comment]
> This would trigger possibly a leak of credentials in debug logs

My wording were bad, I certainly didn't mean to expose username/api key (not that it's possible since api keys are encrypted with travis' key)

> Not sure we are able to differentiate no credentials from bad credentials

Actually I found out the cause was #86, so I guess all PR from non-owner/non-contributor will fail with encrypted env, because it won't be loaded for security reasons....

most repo just remove saucelab test from PR check...
