### ISSUE TITLE
Broken in firefox 47

### ISSUE THREAD

**Issue by jscissr** [defunctzombie/zuul#291]
When I run zuul with latest firefox (47), the test doesn't complete and tries to restart a few times. In the Saucelabs logs, I see this error:

    Error: Permission denied to access property "zuul_msg_bus" (WARNING: The server did not provide any stacktrace information)

**Comment by mappum** [comment]
I'm getting this too. Pretty frustrating since it makes all my CI tests fail and Greenkeeper spams me with "build is breaking" notifications.

**Comment by vvo** [comment]
This is a selenium global issue. Fixed in selenium should be deployed in saucelabs at some point, they will announce it on their twitter account
