### ISSUE TITLE
How to trigger XHTML mode

### ISSUE THREAD

**Issue by rafalwrzeszcz** [defunctzombie/zuul#299]
Is there any way to trigger XHTML page rendering to check compatibility with XHTML? Or at least specify custom headers (usually specifying `Content-Type: application/xhtml+xml` is what tells browser it's XHTML not HTML)?

**Comment by vvo** [comment]
I am not sure to follow your usecase, do you want to validate the testing webpage that is created by zuul for XHTML validation? What would be the usecase/benefit of doing this for you.

**Comment by rafalwrzeszcz** [comment]
To make sure my library works fine with XHTML apps?

**Comment by vvo** [comment]
I think the current zuul test runner webpage is not aware and not able to switch to XHTML.

I don't think this should belong to zuul to have this option. It's an edge case that you could ensure in E2E testing.
