### ISSUE TITLE
Is there a reason behind my travis-ci/saucelabs integration problem

### ISSUE THREAD

**Issue by bitinn** [defunctzombie/zuul#302]
I have not been able to figure out this one for months.

My travis and zuul config looks like these:

- https://github.com/bitinn/vdom-parser/blob/master/.zuul.yml
- https://github.com/bitinn/vdom-parser/blob/master/.travis.yml

While my test result is here:

- https://travis-ci.org/bitinn/vdom-parser/builds/138688252

I can't figure out why the build fails for some of my target devices for no reasons, and errors message like these don't tell me a lot on what ran wrong...

```
zuul browser error (firefox@47: [eval("(window.zuul_msg_bus ? window.zuul_msg_bus.splice(0, 1000) : []);")] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: Error: Permission denied to access property "zuul_msg_bus" (WARNING: The server did not provide any stacktrace information)
```

Is it a network problem? is it a config problem? I am 99.9% certain it has nothing to do with my tests.

**Comment by diffalot** [comment]
I just ran into a similar problem with tests failing on chrome.  In my case I was logging a fairly large object to the console, and when i removed that, it went a lot better.

**Comment by bitinn** [comment]
unfortunately it's not the case for me. i see `github/fetch` repo has removed saucelabs integration too, i should probably do that and manually run test locally instead...
