### ISSUE TITLE
Usage with babel?

### ISSUE THREAD

**Issue by olalonde** [defunctzombie/zuul#311]
I'm trying to get zuul working on https://github.com/olalonde/node-yelp

I installed zuul `npm install --save-dev zuul` and updated my package.json file:

```diff
diff --git a/package.json b/package.json
index 5ee1bff..36f6396 100644
--- a/package.json
+++ b/package.json
@@ -9,6 +9,7 @@
     "clean": "rimraf ./lib",
     "pretest": "npm run lint",
     "test": "babel-node test/*.js",
+    "test-browser-local": "zuul --local -- test/*.js",
     "preversion": "npm test",
     "version:auto": "npm version $(conventional-recommended-bump --preset=angular)",
     "postversion": "git push --tags && git push",
@@ -41,7 +42,8 @@
     "cz-conventional-changelog": "^1.1.4",
     "eslint": "^1.9.0",
     "eslint-config-airbnb": "^1.0.0",
-    "rimraf": "^2.4.3"
+    "rimraf": "^2.4.3",
+    "zuul": "^3.11.1"
   },
   "config": {
     "commitizen": {
```

This is not working because I run my tests with `babel-node`. Is there any way to tell zuul to compile everything with babel?

**Comment by vvo** [comment]
Would that: https://github.com/hden/zuul-babel-power-assert

work for you?

**Comment by olalonde** [comment]
Thanks, seems to work with the browserify option now https://github.com/olalonde/node-yelp/commit/3ec338506883a7daae9f886eafb2c2c00e756b1a
