### ISSUE TITLE
Basic browser list expressions

### ISSUE THREAD

**Issue by btd** [defunctzombie/zuul#312]
Hi, there. It is awesome project. It makes testing should.js in browser very simple task.

What i wanted always it is support very basic expressions like .zuul.yml:
```
browsers:
  - name: chrome
    version: latest-3..latest
```

or maybe browserlist integration (it will excepts browsers, need to create intersection with what saucelabs have).

Thanks.

**Comment by josephfrazier** [comment]
I think this particular syntax is already supported, but without the initial `latest`. From the [wiki](https://github.com/defunctzombie/zuul/wiki/Zuul.yml):

---

Range of versions with negative start index
``` yaml
browsers:
  - name: firefox
    version: -2..latest
```
This example would test the latest three stable versions of Firefox (latest - 2, latest - 1, latest).

**Comment by btd** [comment]
Sorry completly miss reply. Thank you. This solve my issue.
