### ISSUE TITLE
Saucelabs badge

### ISSUE THREAD

**Issue by alessioalex** [defunctzombie/zuul#98]
Hey,

Is there any way I can get a badge for my project? I saw that I need to setup a build id or something (I searched through the saucelabs website) ..? However I didn't find anything on the zuul wiki.

Can somebody help me out?

Thanks

**Comment by andyhu** [comment]
After tried many time, I have found the reason why saucelabs shows an unknown barge even though all my tests has passed. Here is the reason from `saucelabs`' documentation:
[https://wiki.saucelabs.com/display/DOCS/Using+Status+Badges+and+the+Browser+Matrix+Widget+to+Monitor+Test+Results](https://wiki.saucelabs.com/display/DOCS/Using+Status+Badges+and+the+Browser+Matrix+Widget+to+Monitor+Test+Results)
> All you have to do is add either markdown or HTML code to your GitHub README or project site that references your Sauce Labs username and access key, and annotate your tests with the REST or WebDriver API. 
What we need here is to use saucelabs api to update the job with an 'passed' field to indicate whether the test has passed on client site and it must be updated explicitly during a separate API call. 
And here is how `karma-runner` module did it: 
[https://github.com/karma-runner/karma-sauce-launcher/blob/18480efcb3bb446b724387b6373ba4bef31f2b5b/lib/sauce_reporter.js#L40](https://github.com/karma-runner/karma-sauce-launcher/blob/18480efcb3bb446b724387b6373ba4bef31f2b5b/lib/sauce_reporter.js#L40)

**Comment by vvo** [comment]
@andyhu I have matrix badges working here: https://github.com/algolia/algoliasearch-helper-js with zuul, not sure what you mean?

**Comment by andyhu** [comment]
Hi @vvo,
Thanks for replying. Here is my [config file](https://github.com/andyhu/node-transliteration/blob/master/.zuul.yml) for zuul. I passed all tests on saucelabs but the badge is still `unknown` (I've managed to update those jobs through a script though).

**Comment by andyhu** [comment]
And did you test it on travis-ci? Travis CI has an addon sauceslabs_connect which seems automatically update the saucelabs job annotation after test, however if we are on a development server, it doesn't work.
For more detailed description about the issue please check here:
#288

**Comment by vvo** [comment]
Yes we are using travis-ci. For faux-jax I still dunno why the badge is not showing, Ill reload tests.

Here's the travis yml for helper: https://github.com/algolia/algoliasearch-helper-js/blob/master/.travis.yml

**Comment by andyhu** [comment]
Thanks for investigating this issue. I'm not sure why in your project it is working fine, but as per saucelabs documentation, for each tests the test launcher must call their api to update the jobs info

**Comment by niftylettuce** [comment]
@vvo did you ever figure out why it was cached/unknown?  I have same issue and it seems like everyone else does - Sauce doesn't tell us why either, even on their official support thread thing... :facepalm:

**Comment by vvo** [comment]
Nope sorry.. good luck!
